from pathlib import Path

_SECTION_COLORS = {
    "rss":    ("linear-gradient(135deg,#667eea,#764ba2)", "#667eea"),
    "github": ("linear-gradient(135deg,#11998e,#38ef7d)", "#11998e"),
    "reddit": ("linear-gradient(135deg,#f7971e,#ffd200)", "#f7971e"),
}
_DEFAULT_COLOR = ("linear-gradient(135deg,#4facfe,#00f2fe)", "#4facfe")

_ICONS = {"rss": "📰", "github": "🐙", "reddit": "🤖"}
_DEFAULT_ICON = "📌"

# One distinct color per source name (cycles through palette)
_SOURCE_PALETTE = [
    "#667eea", "#e53e3e", "#38a169", "#d69e2e", "#3182ce",
    "#805ad5", "#dd6b20", "#319795", "#e91e8c", "#2d3748",
]

_TEMPLATES_DIR = Path(__file__).parent / "templates"


def _escape(t: str) -> str:
    return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def _safe_url(url: str) -> str:
    return url if url.startswith(("http://", "https://")) else "#"


def _slug(t: str) -> str:
    return t.lower().replace(" ", "-").replace("/", "-")


# ── CSS / JS loaded from template files at import time ────────────────────────

_CSS = (_TEMPLATES_DIR / "style.css").read_text()
_JS  = (_TEMPLATES_DIR / "digest.js").read_text()

# ── HTML template ─────────────────────────────────────────────────────────────

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Daily Digest — {date}</title>
  <style>{css}</style>
</head>
<body>

<header class="masthead">
  <div class="masthead-name">&#9733; The Daily Digest &#9733;</div>
  <div class="masthead-sub">Your personal newspaper, curated by AI</div>
  <div class="masthead-meta">
    <span>&#128197; {date}</span>
    <span>&#183;</span>
    <span>&#128279; {item_count} stories</span>
    <span>&#183;</span>
    <span>&#9733; 5 highlights</span>
  </div>
</header>

<nav class="section-nav">{nav_html}</nav>

<div class="page">

  <!-- TOP 5 HIGHLIGHTS -->
  <div class="divider" id="highlights">&#9733; Top 5 Highlights of the Day</div>
  <div class="highlights-grid">{highlights_html}</div>

  <!-- ALL RSS STORIES -->
  <div class="divider" id="top-stories">&#128240; All Stories</div>
  <div class="rss-section">
    <div class="rss-section-header" style="background:linear-gradient(135deg,#667eea,#764ba2)">
      <span class="sec-icon">&#128240;</span>
      <span class="sec-title">RSS News Feed</span>
      <span class="sec-count">{rss_count} stories</span>
    </div>
    <div class="source-tabs">{tabs_html}</div>
    <ul class="article-list">{rss_items_html}</ul>
  </div>

  <!-- OTHER SECTIONS (GitHub, Reddit) -->
  {other_html}

  <div class="footer">
    Generated by daily-info-digest &middot; Summarized with Claude AI
  </div>
</div>

<script>{js}</script>
</body>
</html>
"""


# ── Helpers ────────────────────────────────────────────────────────────────────

def _source_color(source: str, source_list: list) -> str:
    try:
        idx = source_list.index(source)
    except ValueError:
        idx = 0
    return _SOURCE_PALETTE[idx % len(_SOURCE_PALETTE)]


def _render_highlights(items: list, highlights: list, source_list: list) -> str:
    if not highlights:
        return ""
    out = ""
    for rank, h in enumerate(highlights[:5], 1):
        idx = h.get("index", 0)
        reason = h.get("reason", "")
        if idx >= len(items):
            continue
        item = items[idx]
        source = item.get("source", "")
        color = _source_color(source, source_list)
        title = _escape(item["title"])
        url = _safe_url(item.get("url", ""))
        card_class = f"hl-card hl-card-{rank - 1}"

        out += f"""
  <div class="{card_class}">
    <div class="hl-accent-bar" style="background:{color}"></div>
    <div class="hl-rank">{rank}</div>
    <div class="hl-body">
      <span class="hl-source-badge" style="background:{color}">{_escape(source)}</span>
      <a class="hl-title" href="{_escape(url)}" target="_blank" rel="noopener">{title}</a>
      {"<p class='hl-reason' style='border-color:" + color + "'>" + _escape(reason) + "</p>" if reason else ""}
    </div>
  </div>"""
    return out


def _render_source_tabs(sources: list) -> str:
    tabs = '<button class="source-tab active" data-source="all">All</button>'
    for src in sources:
        tabs += f'<button class="source-tab" data-source="{_escape(src)}">{_escape(src)}</button>'
    return tabs


def _render_rss_items(items: list, highlight_indices: set, source_list: list) -> str:
    out = ""
    for i, item in enumerate(items):
        source = item.get("source", "")
        color = _source_color(source, source_list)
        title = _escape(item["title"])
        url = _safe_url(item.get("url", ""))
        ai_summary = item.get("ai_summary", "")  # legacy compat — no longer drives dropdown
        core_idea = item.get("core_idea", "") or ""
        key_points_raw = item.get("key_points", []) or []
        non_empty_key_points = [kp for kp in key_points_raw if kp and kp.strip()]
        has_dropdown = bool(non_empty_key_points)
        has_core_idea = bool(core_idea and core_idea.strip())
        is_hl = i in highlight_indices
        hl_class = " highlighted" if is_hl else ""
        hl_tag = '<span class="highlight-tag">&#9733; Highlight</span>' if is_hl else ""

        if has_core_idea or has_dropdown:
            # Build the dropdown body: numbered key-points list (D-05, D-06, D-07) + read-more (D-08)
            if has_dropdown:
                kp_rows = ""
                for n, kp in enumerate(non_empty_key_points, 1):
                    kp_rows += (
                        f'<li><span class="article-keypoint-chip" style="background:{color}">{n}</span>'
                        f'<span>{_escape(kp)}</span></li>'
                    )
                key_points_html = f'<ul class="article-keypoints">{kp_rows}</ul>'
            else:
                key_points_html = ""

            read_more = (
                f'<a class="article-read-more" href="{_escape(url)}" target="_blank" rel="noopener">Read full article &#8599;</a>'
                if url != "#" else ""
            )

            details_html = f"""<details class="article-details">
          <summary><span class="article-title-text">{title}</span><i class="article-toggle-icon">&#9660;</i></summary>
          <div class="article-ai-summary" style="border-color:{color}">{key_points_html}{read_more}</div>
        </details>"""

            # D-02: core_idea sits below the title-row (the <summary>), as a sibling of <details>,
            # so it is always visible without expanding (REND-01).
            core_idea_html = (
                f'<p class="article-core-idea" style="border-color:{color}">{_escape(core_idea)}</p>'
                if has_core_idea else ""
            )
            content = details_html + core_idea_html
        elif url != "#":
            content = f'<a class="article-link" href="{_escape(url)}" target="_blank" rel="noopener">{title}</a>'
        else:
            content = f'<span class="article-link">{title}</span>'

        out += f"""
    <li class="article-item{hl_class}" data-source="{_escape(source)}">
      <span class="article-num">{i + 1}</span>
      <div class="article-content">
        <div class="article-meta-top">
          <span class="source-chip" style="background:{color}">{_escape(source)}</span>
          {hl_tag}
        </div>
        {content}
      </div>
    </li>"""
    return out


def _render_accordion(section: dict, open_first: bool) -> str:
    stype = section.get("type", "rss")
    gradient, accent = _SECTION_COLORS.get(stype, _DEFAULT_COLOR)
    icon = _ICONS.get(stype, _DEFAULT_ICON)
    slug = _slug(section["title"])
    count = len(section["items"])
    open_attr = " open" if open_first else ""

    summary_html = ""
    if section.get("summary"):
        summary_html = (
            f'<div class="acc-summary-box" style="border-color:{accent}">'
            f'{_escape(section["summary"])}</div>'
        )

    items_html = ""
    for i, item in enumerate(section["items"], 1):
        title = _escape(item["title"])
        url = _safe_url(item.get("url", ""))
        ai_summary = item.get("ai_summary", "")
        badges = []
        if "stars" in item:
            badges.append(f'<span class="meta-badge">&#11088; {_escape(str(item["stars"]))}</span>')
        if "score" in item:
            badges.append(f'<span class="meta-badge">&#8679; {item["score"]}</span>')
        meta_html = f'<div class="acc-meta">{"".join(badges)}</div>' if badges else ""

        if ai_summary:
            read_more = (
                f'<a class="acc-read-more" href="{_escape(url)}" target="_blank" rel="noopener">Read full article &#8599;</a>'
                if url != "#" else ""
            )
            inner = f"""<details class="acc-details">
            <summary><span class="acc-title-text">{title}</span><i class="acc-toggle-icon">&#9660;</i></summary>
            <div class="acc-ai-summary" style="border-color:{accent}">{_escape(ai_summary)}{read_more}</div>
          </details>{meta_html}"""
        elif url != "#":
            inner = f'<a class="acc-link" href="{_escape(url)}" target="_blank" rel="noopener">{title}</a>{meta_html}'
        else:
            inner = f'<span class="acc-link">{title}</span>{meta_html}'

        items_html += f"""
      <li class="acc-item">
        <div class="acc-index" style="background:{accent}">{i}</div>
        <div style="flex:1">{inner}</div>
      </li>"""

    return f"""
  <details class="accordion"{open_attr} id="{slug}">
    <summary style="background:{gradient}">
      <span class="sec-icon">{icon}</span>
      <span class="sec-title">{_escape(section["title"])}</span>
      <span class="sec-count">{count} stories</span>
      <i class="acc-chevron">&#9660;</i>
    </summary>
    <div class="acc-body">
      {summary_html}
      <ul class="acc-list">{items_html}
      </ul>
    </div>
  </details>"""


# ── Public entry point ────────────────────────────────────────────────────────

def render_html_digest(sections: list, output_path: Path, today: str) -> None:
    rss_section    = next((s for s in sections if s.get("type") == "rss"), None)
    other_sections = [s for s in sections if s.get("type") != "rss"]

    rss_items = rss_section["items"] if rss_section else []
    highlights = rss_section.get("highlights", []) if rss_section else []
    highlight_indices = {h["index"] for h in highlights}

    # ordered unique sources
    seen: list = []
    for item in rss_items:
        src = item.get("source", "")
        if src and src not in seen:
            seen.append(src)
    source_list = seen

    # nav pills
    nav_html = '<a class="nav-pill" href="#highlights">&#9733; Highlights</a>'
    nav_html += '<a class="nav-pill" href="#top-stories">&#128240; All Stories</a>'
    for s in other_sections:
        nav_html += f'<a class="nav-pill" href="#{_slug(s["title"])}">{_ICONS.get(s.get("type"), _DEFAULT_ICON)} {_escape(s["title"])}</a>'

    highlights_html = _render_highlights(rss_items, highlights, source_list)
    tabs_html       = _render_source_tabs(source_list)
    rss_items_html  = _render_rss_items(rss_items, highlight_indices, source_list)

    other_label = ""
    other_cards = ""
    if other_sections:
        other_label = '<div class="divider">&#128279; More Sources</div>'
        other_cards = '<div class="other-sections">' + "".join(
            _render_accordion(s, i == 0) for i, s in enumerate(other_sections)
        ) + "</div>"
    other_html = other_label + other_cards

    item_count = sum(len(s["items"]) for s in sections)

    html = _HTML_TEMPLATE.format(
        date=today,
        css=_CSS,
        js=_JS,
        item_count=item_count,
        rss_count=len(rss_items),
        nav_html=nav_html,
        highlights_html=highlights_html,
        tabs_html=tabs_html,
        rss_items_html=rss_items_html,
        other_html=other_html,
    )
    output_path.write_text(html, encoding="utf-8")
